"""Generate the committed TypeScript model registry from the Python source of truth."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from caelo_core.models.registry import get_model_registry  # noqa: E402

TARGET = ROOT / "desktop" / "src" / "renderer" / "src" / "lib" / "generated" / "models.ts"


def render() -> str:
    registry = get_model_registry()
    providers = [p.to_dict() for p in registry.providers()]
    models = [m.to_dict() for m in registry.models()]
    provider_ids = " | ".join(json.dumps(p["id"]) for p in providers)
    model_ids = " | ".join(json.dumps(m["id"]) for m in models)
    payload = json.dumps({"providers": providers, "models": models}, ensure_ascii=False, indent=2)
    return f"""// GENERATED by scripts/generate_model_types.py. Do not edit by hand.
export type ProviderId = {provider_ids}
export type GeneratedModelId = {model_ids}
export type MediaType = 'chat' | 'image' | 'video'

export const GENERATED_MODEL_REGISTRY = {payload} as const
"""


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = render().replace("\r\n", "\n")
    current = TARGET.read_text(encoding="utf-8").replace("\r\n", "\n") if TARGET.exists() else ""
    if args.check:
        if current != expected:
            print(f"Generated registry is stale: {TARGET}")
            return 1
        return 0
    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(expected, encoding="utf-8", newline="\n")
    print(TARGET)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
