"""Generate the committed TypeScript model registry from the Python source of truth."""

from __future__ import annotations

import argparse
import json
import sys
import types
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

# Code generation needs only the model registry, which is pure stdlib + `config`.
# Importing `caelo_core` normally would run its `__init__`, which builds the FastAPI
# app — so `npm run typecheck` would demand the whole sidecar dependency tree on every
# machine that only touches the renderer (and on the frontend CI job, which installs
# no Python deps). Registering a bare package stub keeps the relative imports inside
# `caelo_core.models` working while skipping that `__init__`.
if "caelo_core" not in sys.modules:
    _pkg = types.ModuleType("caelo_core")
    _pkg.__path__ = [str(ROOT / "caelo_core")]  # type: ignore[attr-defined]
    sys.modules["caelo_core"] = _pkg

from caelo_core.models.registry import get_model_registry  # noqa: E402

TARGET = ROOT / "desktop" / "src" / "renderer" / "src" / "lib" / "generated" / "models.ts"


def render() -> str:
    registry = get_model_registry()
    providers = [p.to_dict() for p in registry.providers()]
    models = [m.to_dict() for m in registry.models()]
    provider_ids = " | ".join(json.dumps(p["id"]) for p in providers)
    model_ids = " | ".join(json.dumps(m["id"]) for m in models)
    payload = json.dumps({"providers": providers, "models": models}, ensure_ascii=False, indent=2)
    return f"""// GENERATED by scripts/generate_model_types.py. Do not edit by hand.
export type ProviderId = {provider_ids}
export type GeneratedModelId = {model_ids}
export type MediaType = 'chat' | 'image' | 'video'

export const GENERATED_MODEL_REGISTRY = {payload} as const
"""


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = render().replace("\r\n", "\n")
    current = TARGET.read_text(encoding="utf-8").replace("\r\n", "\n") if TARGET.exists() else ""
    if args.check:
        if current != expected:
            print(f"Generated registry is stale: {TARGET}")
            return 1
        return 0
    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(expected, encoding="utf-8", newline="\n")
    print(TARGET)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
